config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  root to: 'orders#show'

  resources :orders do

        resources :items

        resources :current_orders

        member do

          get "pay"

          get "cart"

        end

        end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current_order.rb
class CurrentOrder < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :restaurant

  has_many :current_orders
  has_many :orders, through: :current_orders

  mount_uploader :image, PhotoUploader

end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user, optional: true
  belongs_to :table

  has_many :current_orders
  has_many :items, through: :current_orders
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
	has_many :tables
	has_many :items

  mount_uploader :image, PhotoUploader

end

app/models/table.rb
class Table < ApplicationRecord
  belongs_to :restaurant
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :orders

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/current_order_controller.rb
class CurrentOrderController < ApplicationController

  def create
    @current_order = CurrentOrder.new(current_order_params)
    @order = Order.find(params[:order_id])
  end

  def new

  end

  private

  def current_order_params
    params.require(:current_order).permit(:quantity, :order_id, :item_id, :item_price)
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController

def show
  @item = Item.find(params[:id])
end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def show

    @order = Order.last
    @restaurant = @order.table.restaurant
    @items = @restaurant.items
    @table = @order.table

    @menu = @items.where(restaurant_id: @restaurant.id)
    @appetizer = @menu.where(food_category: "food_app")
    @food = @menu.where(food_category: "food_main")
    @drink = @menu.where(food_category: "drink")
    @dessert = @menu.where(food_category: "food_dessert")
  end


  def update
    @order = Order.find(params[:id])
  end

  def pay
    @order = Order.last
    render "current_order/pay"
  end

def cart
    @order = Order.last
    render "pages/cart"
  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
end

app/controllers/table_controller.rb
class TableController < ApplicationController
end

app/controllers/user_controller.rb
class UserController < ApplicationController
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/current_order/pay.html.erb
<div class="restaurant-header">
  <p>Thanks for visiting: <strong><%= Restaurant %></strong></p>
</div>

<div class="header-image" style="background-image: url('https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80');   background-size: cover;">
</div>


  <div class="container-wrapper">

    <h5>Choose a Payment option:</h5>
    <hr>

<!-- Payment Options -->
<div class="pay-options">

<!-- <div class="applepay"><i class="fab fa-apple-pay"></i></div>

<div class="paypal"><i class="fab fa-cc-paypal"></i></div>

<div class="creditcart"><i class="fab fa-cc-mastercard"></i></div>

<div class="Stripe"><i class="fab fa-cc-stripe"></i></div> -->

<!-- TABS -->

<!-- Button trigger modal -->
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#applepay">
  <i class="fab fa-apple-pay"></i>
</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#paypal">
  <i class="fab fa-cc-paypal"></i>
</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#mastercart">
  <i class="fab fa-cc-mastercard"></i>
</button>
<button type="button" class="btn btn-primary" data-toggle="modal" data-target="#stripe">
  <i class="fab fa-cc-stripe"></i>
</button>
<!-- Modal -->
<!-- Apple Pay -->
<div class="modal fade" id="applepay" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Apple Pay</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Pay</button>
      </div>
    </div>
  </div>
</div>
<!-- END Apple Pay -->

<!-- TABS -->

</div>

<hr>
<!-- END Payment Options -->

<div class="pay-confirm">


</div>


  </div>

app/views/items/show.html.erb
<!-- Description of the meal -->
<div class="container-wrapper">
    <div class="item-details">
        <div class="item-shoppingcard">
            <!-- <p>1</p> -->
            <%= link_to ' <i class="fas fa-shopping-cart"></i> '.html_safe, root_path %>
        </div>
        <h3>
            <%= @item.name %>
        </h3>
        <p>
            <%= @item.description %>
        </p>
    </div>
    <!-- Amount of the meal -->
    <div class="item-amount-buttons">
        <div class="item-amount">
            <div class="item-amount-smaller">
                <p>-</p>
            </div>
            <div class="item-amount-display">
                <p>1</p>
            </div>
            <div class="item-amount-greater">
                <p>+</p>
            </div>
        </div>
        <div class="item-price">
            <h2>
                <span id="price">
                    <%=@item.price %></span> €</h2>
        </div>
    </div>
</div>
<div class="item-menu">
    <%= simple_form_for @current_order, url: order_current_orders_path do |f| %>
    <%= f.input :quantity, :as => :hidden, :input_html => { id: :input, :value => "1" } %>
    <%= f.input :item_price, :as => :hidden, :input_html => { :value => @item.price } %>
    <%= f.input :item_id, :as => :hidden, :input_html => { :value => @item.id } %>
    <%= f.input :order_id, :as => :hidden, :input_html => { :value => @order.id } %>
    <%= f.button :submit, 'Add to cart',name: "add_to_cart", class: "btn btn-primary"  %>
    <%= f.button :submit, 'Order now', name: 'order_now', class: "btn btn-primary" %>
    <% end %>
    <!-- simple form for -->
    <!-- hide field either with class of display: none -->
    <!-- f.hidden_field pass in the item id from @item.price -->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <script src="https://kit.fontawesome.com/36197ad289.js"></script>
    <link href="https://fonts.googleapis.com/css?family=Montserrat:300,400,500,600&display=swap" rel="stylesheet">
    <title>TODO</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all' %>
    <%#= stylesheet_pack_tag 'application', media: 'all' %> <!-- Uncomment if you import CSS in app/javascript/packs/application.js -->
  </head>
  <body>
    <%= yield %>
    <%= javascript_include_tag 'application' %>
    <%= javascript_pack_tag 'application' %>
  </body>
</html>

app/views/orders/show.html.erb
<div class="restaurant-header">
  <p>Welcome to: <strong><%= @restaurant.name %></strong></p>
</div>

<div class="header-image" style="background-image: url('https://images.unsplash.com/photo-1533777857889-4be7c70b33f7?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=1500&q=80');   background-size: cover;">



<!-- TAPES  -->
<div class="container-wrapper">
    <ul class="nav nav-pills mb-3" id="pills-tab" role="tablist">
        <li class="nav-item">
            <a class="nav-link active" id="pills-home-tab" data-toggle="pill" href="#pills-home" role="tab" aria-controls="pills-home" aria-selected="true">Food</a>
        </li>
        <li class="nav-item">
            <a class="nav-link" id="pills-profile-tab" data-toggle="pill" href="#pills-profile" role="tab" aria-controls="pills-profile" aria-selected="false">Drinks</a>
        </li>
    </ul>
    <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
            <!-- Food content Tab -->
<hr>
            <h4>Appetizer:</h4>

            <div class="cart-content">
    <% @appetizer.each do |n| %>
    <%= link_to order_item_path(@order, n) do %>
    <div class="card-trip">
        <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
        <div class="card-trip-infos">
            <div>
                <h2>
                    <%= n.name %>
                </h2>
                <p>
                    <%=n.card_info  %>
                </p>
            </div>
            <h2 class="card-trip-pricing">£
                <%= n.price %>
            </h2>
            <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> -->
        </div>
    </div>
    <% end %>
    <% end %>
</div>


            <h4>Main Dishes:</h4>
            <% @food.each do |n| %>
            <%= link_to order_item_path(@order, n) do %>
            <p>
                <%= n.name %>
            </p>
            <% end %>
            <% end %>
            <h4>Desserts:</h4>
            <% @dessert.each do |n| %>
            <%= link_to order_item_path(@order, n) do %>
            <p>
                <%= n.name %>
            </p>
            <% end %>
            <% end %>
        </div>
        <hr>
        <!-- END: Food content Tab -->
        <div class="tab-pane fade" id="pills-profile" role="tabpanel" aria-labelledby="pills-profile-tab">
            <!-- Drinks content Tab -->
             <div class="cart-content">

            <% @drink.each do |n| %>
            <%= link_to order_item_path(@order, n) do %>

            <div class="card-trip">
                <img src="https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/greece.jpg" />
                <div class="card-trip-infos">
                    <div>
                        <h2><%= n.name %></h2>
                        <p><%=n.card_info  %></p>
                    </div>
                    <h2 class="card-trip-pricing">£ <%= n.price %> </h2>
                    <!-- <img src="https://kitt.lewagon.com/placeholder/users/krokrob" class="card-trip-user avatar-bordered" /> -->
                </div>
            </div>
            <% end %>
            <% end %>

            </div></div>
    </div>




    <p>----------------</p>
    <h2>Order:</h2>
    <p>
        <%= @order   %>
    </p>
    <h3>Order ID:</h3>
    <p>
        <%= @order.id   %>
    </p>
    <h3>Restaurant:</h3>
    <p>
        <%= @restaurant   %>
    </p>
    <p>----------------</p>
    <h2>Restaurant Name:</h2>
    <%= @restaurant.name  %>
    <%= @items %>
    <%= @table  %>
</div>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>